### ISSUE TITLE
Integrate wasm-pack into the book

### ISSUE THREAD

**Issue by mgattozzi** [rust-lang-nursery/rust-wasm#78]
@ashleygwilliams will be releasing 0.1 of [wasm-pack](https://github.com/ashleygwilliams/wasm-pack) this Friday. We'll want to integrate this as part of the book. This will be one of the first few tools integrated into the book on how to use it. Future work includes other tools we have reccomended such as std-web.

Tasks:
- [x] Setup a summary/introduction page
- [x] Setup a top level and subsections for it in the SUMMARY.md file
- [x] Basic setup
    - [x] Refer to setup for rust
    - [x] Have an NPM account/way to publish to NPM
- [x] Intialize a project/import the right things
- [x] Make functions for wasm
- [x] Package and send it to NPM - @ashleygwilliams will do this part
- [x] Setup a small example repo
- [x] Import the NPM package
- [x] Call the code and run it
- [x] Conclusion

**Comment by mgattozzi** [comment]
Current working branch for this is here: https://github.com/mgattozzi/rust-wasm/tree/wasm-pack

**Comment by mgattozzi** [comment]
Managed to go through and come up with a decent example as well as a few things to help improve the tool so the writing is now well underway.

Just want to say this is an exciting tool that pretty much just works so get ready!

**Comment by mgattozzi** [comment]
PR open in #86

**Comment by mgattozzi** [comment]
Closed in #86
